= fpm-tree(1)

:doctype: manpage
:release-version: 0.1.0
:manmanual: fpm-tree command

== Name

fpm-tree - Display a tree visualization of the package dependency graph

== Synopsis

*fpm-tree* [_OPTION_]...

== Description

The fpm-tree(1) command displays a tree-view of the package dependency graph.
The packages are displayed in the order encountered during a depth-first search
of the tree.

== Options

*--charset* _CHARSET_::
  Choose the character set to use for the tree. Valid values are "utf8" (default) or
  "ascii".

*--prefix* _PREFIX_::
  Sets how each line is displayed. The _PREFIX_ value can be one of:

  * `indent` (default) -- Shows each line indented as a tree
  * `depth` -- Show as a list, with the numeric depth printed before each entry
  * `none` -- Show as a flat list

*--depth* _DEPTH_::
  Maximum dependency _DEPTH_ to display. A depth of 1 displays the
  direct dependencies.

*--no-dedupe*::
  Do not de-duplicate repeated dependencies. If a dependency has been
  displayed already, further occurences of the same package will not
  repeat the dependencies, but include a `+(*)+` instead.

*--version*::
  Print version number

*-h, --help*::
  Prints help information

== Exit status

Exits with 0 on success, and >0 if an error occurs.

== Resources

*Project web site:* https://github.com/ivan-pi/fpm-deps
